src/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from . import db

auth = Blueprint("auth", __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Connexion réussie.', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.index'))
            else:
                flash('Identifiants incorrects!', category='error')
        else:
            flash('Cet email n\'existe pas!', category='error')

    return render_template('login.html', user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        firstname = request.form.get('firstname')
        lastname = request.form.get('lastname')
        email = request.form.get('email')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email)
        if user:
            flash('Un utilisateur avec cet email existe déjà! Choisissez un autre.', category='error')

        if len(firstname) < 2:
            flash('Le prénom doit avoir aumoins 4 caractères !', category='error')
        elif len(lastname) < 4:
            flash('Le nom doit avoir aumoins 4 caractères !', category='error')
        elif len(email) < 3:
            flash('L"email saisi est invalide !', category='error')
        elif len(password1) < 6:
            flash('Le mot de passe doit avoir aumoins 6 caractères !', category='error')
        elif password1 != password2:
            flash('Les deux mots de passe ne sont pas identiques !', category='error')
        else:
            pwd_hash = generate_password_hash(password1, method='sha256')
            new_user = User(firstname=firstname, lastname=lastname, email=email, password=pwd_hash)
            db.session.add(new_user)
            db.session.commit()

            flash('Compte crée correctement.', category='success')
            return redirect(url_for('views.index'))

    return render_template('register.html', user=current_user)

src/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, login_required, current_user
from datetime import datetime
from .models import Business, Expense, Sale
from . import db

views = Blueprint("views", __name__)


@views.route("/")
def index():
    return render_template('index.html', user=current_user)


@views.route('/dashboard')
@login_required
def dashboard():
    list_expenses = list_total_expense_per_project()
    list_sales = list_total_sales_per_project()

    new_list_expenses = []
    # create last dict(key: str, val: list)
    print('-----Final------')
    for key in list_expenses.keys():
        if key in list_sales:
            list_expenses[key].append(list_sales[key][0])
        else:
            list_expenses[key].append(0)
    # convert list of dicts to list of lists [key, [vals]]
    for key, vals in list_expenses.items():
        new_list_expenses.append([key, vals])

    stats = [all_projects(), active_projects(), closed_projects()]

    return render_template('dashboard.html', user=current_user, new_list_expenses=new_list_expenses, stats=stats)


def list_total_expense_per_project(): # active project ==> add status(active/closed) field on project
    all_expenses = Expense.query.all()

    # sum expenses per project and create dict per project with dates, status and total expenses
    total_expenses_per_project = {}
    for each_expense in all_expenses:
        if each_expense.business_rel.title not in total_expenses_per_project:
            temp_amount = each_expense.amount
            total_expenses_per_project[each_expense.business_rel.title] = [temp_amount, each_expense.business_rel.date_start, each_expense.business_rel.date_end, each_expense.business_rel.active]

        else:
            total_expenses_per_project[each_expense.business_rel.title][0] += each_expense.amount

    return total_expenses_per_project


def list_total_sales_per_project():
    sales = Sale.query.all()

    # sum sales per project and create dict per project with dates, status and total revenues
    total_sales_per_project = {}
    for each_sale in sales:
        if each_sale.business_rel.title not in total_sales_per_project:
            temp_amount = each_sale.amount
            total_sales_per_project[each_sale.business_rel.title] = [temp_amount,
               each_sale.business_rel.date_start,
               each_sale.business_rel.date_end,
               each_sale.business_rel.active
               ]
        else:
            total_sales_per_project[each_sale.business_rel.title][0] += each_sale.amount

    return total_sales_per_project


def all_projects():
    all_registered_projects = Business.query.count()
    return all_registered_projects


def active_projects():
    all_active_projects = Business.query.filter_by(active=True).count()
    return all_active_projects


def closed_projects():
    all_active_projects = Business.query.filter_by(active=False).count()
    return all_active_projects


@views.route('/projects', methods=['GET', 'POST'])
@login_required
def project():
    if request.method == 'POST':
        title = request.form.get('title')
        description = request.form.get('description')
        op_checked = request.form.get("active")
        if op_checked:
            active = True
        estimated_cost = int(request.form.get('estimated_cost'))
        estimated_revenue = int(request.form.get('estimated_revenue'))

        y, m, d = request.form.get('date_start').split('-')
        date_start = datetime(int(y), int(m), int(d))

        y, m, d = request.form.get('date_end').split('-')
        date_end = datetime(int(y), int(m), int(d))

        # end date should be greater than start date
        if date_end <= date_start:
            flash('La date de fin doit être supérieure à la date de début', 'error')

        else:
            new_project = Business(title=title, description=description, active=active, date_start=date_start, date_end=date_end, estimated_cost=estimated_cost, estimated_revenue=estimated_revenue, user_id=current_user.id)
            db.session.add(new_project)
            db.session.commit()
            flash('Projet créé avec succès', category='success')

    return render_template('projects.html', user=current_user, projects=Business.query.all())


@views.route('/project_edit/<int:id>', methods=['GET', 'POST'])
@login_required
def project_edit(id):
    project = Business.query.get_or_404(id)

    if request.method == 'POST':
        project.title = request.form.get('title')
        project.description = request.form.get('description')
        op_checked = request.form.get("active")
        if op_checked:
            project.active = True
        project.estimated_cost = int(request.form.get('estimated_cost'))
        project.estimated_revenue = int(request.form.get('estimated_revenue'))

        y, m, d = request.form.get('date_start').split('-')
        project.date_start = datetime(int(y), int(m), int(d))

        y, m, d = request.form.get('date_end').split('-')
        project.date_end = datetime(int(y), int(m), int(d))

        db.session.commit()
        flash('Projet mis à jour', category='success')
        return redirect(url_for('views.project'))
    else:
        return render_template('project_edit.html', project=project, user=current_user)


@views.route('/project_delete/<int:id>')
@login_required
def project_delete(id):
    project_to_delete = Business.query.get_or_404(id)

    if project_to_delete:
        db.session.delete(project_to_delete)
        db.session.commit()
        flash('Projet supprimé avec succès.', 'success')
        return redirect(url_for('project'))


@views.route('/expenses', methods=['GET', 'POST'])
@login_required
def expense():
    if request.method == 'POST':
        amount = request.form.get("amount")
        category = request.form.get("category")

        y, m, d = request.form.get('date_transaction').split('-')
        date_transaction = datetime(int(y), int(m), int(d))

        financier = request.form.get('financier')
        description = request.form.get("description")
        business_id = request.form.get("project_id")

        new_expense = Expense(amount=amount, category=category, date_transaction=date_transaction, financier=financier, description=description, business_id=business_id, user_id=current_user.id)
        db.session.add(new_expense)
        db.session.commit()
        flash('Dépense créée avec succès', category='success')

    return render_template('expenses.html', user=current_user, expenses=Expense.query.all(), projects=Business.query.all())


@views.route('/expense_edit/<int:id>', methods=['GET', 'POST'])
@login_required
def expense_edit(id):
    expense_to_edit = Expense.query.get_or_404(id)

    if request.method == 'POST':
        expense_to_edit.amount = request.form.get("amount")
        expense_to_edit.category = request.form.get("category")

        y, m, d = request.form.get('date_transaction').split('-')
        expense_to_edit.date_transaction = datetime(int(y), int(m), int(d))

        expense_to_edit.financier = request.form.get("financier")
        expense_to_edit.description = request.form.get("description")
        expense_to_edit.business_id = request.form.get("project_id")

        db.session.commit()
        flash("Transaction dépense modifiée avec succès.", category="success")
        return redirect(url_for('views.expense'))

    return render_template('expense_edit.html', expense=expense_to_edit, user=current_user, projects=Business.query.all())


@views.route('/expense_delete/<int:id>')
def expense_delete(id):
    expense_to_delete = Expense.query.get_or_404(id)

    if expense_to_delete:
        db.session.delete(expense_to_delete)
        db.session.commit()
        flash('Transaction dépense supprimé avec succès.', category='success')
        return redirect(url_for('views.expense'))


@views.route('/sales', methods=['GET', 'POST'])
@login_required
def sale():
    if request.method == 'POST':
        amount = request.form.get("amount")
        y, m, d = request.form.get('date_transaction').split('-')
        date_transaction = datetime(int(y), int(m), int(d))

        description = request.form.get("description")
        business_id = request.form.get("project_id")

        new_sale = Sale(amount=amount, date_transaction=date_transaction, description=description, business_id=business_id, user_id=current_user.id)
        db.session.add(new_sale)
        db.session.commit()
        flash('Transaction de vente créée avec succès', category='success')

    return render_template('sales.html', user=current_user, sales=Sale.query.all(), projects=Business.query.all())


@views.route('/sale_edit/<int:id>', methods=['GET', 'POST'])
@login_required
def sale_edit(id):
    sale_to_edit = Sale.query.get_or_404(id)

    if request.method == 'POST':
        sale_to_edit.amount = request.form.get("amount")
        y, m, d = request.form.get('date_transaction').split('-')
        sale_to_edit.date_transaction = datetime(int(y), int(m), int(d))

        sale_to_edit.description = request.form.get("description")
        sale_to_edit.business_id = request.form.get("project_id")

        db.session.commit()
        flash("Transaction de vente modifiée avec succès.", category="success")
        return redirect(url_for('views.sale'))

    return render_template('sale_edit.html', sale=sale_to_edit, user=current_user, projects=Business.query.all())


@views.route('/sale_delete/<int:id>')
def sale_delete(id):
    sale_to_delete = Sale.query.get_or_404(id)

    if sale_to_delete:
        db.session.delete(sale_to_delete)
        db.session.commit()
        flash('Transaction de vente supprimée avec succès.', category='success')
        return redirect(url_for('sale'))

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Home {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark menu_class">
        <a class="navbar-brand" href="{{ url_for('views.index') }}" title="wood icons"><img src="{{ url_for('static', filename='images/wood-cutting.png') }}" width="24px" height="24px"/></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('views.index') }}">Accueil</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('views.project') }}">Projets</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('views.expense') }}">Dépenses</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('views.sale') }}">Ventes</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('views.dashboard') }}">Dashboard</a>
            </li>
            </ul>
            <ul class="navbar-nav">
              <!-- To be pushed to the right -->
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.logout') }}"><span class="fa fa-user"><i>&nbsp;{{current_user.firstname}}</i>&nbsp; &nbsp; &nbsp;</span> Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.register') }}">Inscription</a>
            </li>
            {% endif %}
          </ul>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
</body>
</html>

src/templates/expenses.html
{% extends 'base.html' %}

{% block title %}Dépenses{% endblock %}}

{% block content %}
    <h1 class="text-center bg-secondary text-white mt-3">Suivi dépenses</h1>
    <div>
        <div class="row justify-content-center">
            <br>
            <div class="form-card col-md-4 mt-5">
                <h5 class="text-center bg-danger-subtle text-white p-3 rounded">Saisie dépense</h5>
                <br />
                <form action="" method="POST">
                  <div class="row">
                      <div class="mb-3 col">
                        <label for="amount" class="form-label">Montant</label>
                        <input type="number" id="amount" class="form-control" name="amount" aria-describedby="emailHelp">
                      </div>
                      <div class="mb-3 col">
                        <label for="category" class="form-label">Catégorie</label>
                        <select class="choice_class form-control" id="category" name="category">
                            <option value="">Choisir catégorie ...</option>
                            <option value="Capital">Capital</option>
                            <option value="MO ouvriers">MO ouvriers</option>
                            <option value="MO supervision">MO supervision</option>
                            <option value="Déplacement">Déplacement</option>
                            <option value="Communication">Communication</option>
                        </select>
                      </div>
                  </div>
                  <div class="mb-3">
                    <label for="description" class="form-label">Libellé</label>
                      <textarea id="description" class="form-control" name="description"></textarea>
                  </div>
                  <div class="row">
                      <div class="mb-3 col">
                        <label for="date_transaction" class="form-label">Date opération</label>
                        <input type="date" id="date_transaction" class="date_class form-control" name="date_transaction">
                      </div>
                      <div class="mb-3 col">
                        <label for="projet_id" class="form-label">Projet lié</label>
                          <select class="choice_class form-control" name="project_id" id="projet_id">
                              <option value="">Choisir projet ...</option>
                              {% for project in projects %}
                              <option value="{{ project.id }}">{{ project.title }}</option>
                              {% endfor %}
                          </select>
                      </div>
                      <div class="mb-3">
                        <label for="financier" class="form-label">Financier</label>
                        <select class="choice_class form-control" id="financier" name="financier">
                            <option value="">Choisir financier ...</option>
                            <option value="François">François</option>
                            <option value="Nick">Nick</option>
                            <option value="Koffi">Koffi</option>
                        </select>
                      </div>
                  </div>
                  <div class="row">
                  <button type="submit" class="btn btn-secondary btn-block">Ajouter</button>
                  </div>
                    <br />
                </form>
            </div>

            <div>
                <br />
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Intitulé</th>
                      <th scope="col">Catégorie</th>
                      <th scope="col">Montant</th>
                      <th> Date dépense</th>
                      <th> Financier</th>
                      <th> Saisie par</th>
                      <th scope="col">Projet lié</th>
                      <th scope="col">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for expense in expenses%}
                    <tr>
                      <th scope="row">{{ expense.id }}</th>
                      <td>{{ expense.description }}</td>
                      <td>{{ expense.category }}</td>
                      <td>{{ "{:,.0f}".format(expense.amount) }}</td>
                      <td>{{ expense.date_transaction.strftime('%d-%m-%Y') }}</td>
                      <td>{{ expense.financier }}</td>
                      <td>{{ expense.user_rel.firstname }} {{ expense.user_rel.lastname }}</td>
                      <td>{{ expense.business_rel.title }}</td>
                      <td>
                        <a href="{{ url_for('views.expense_edit', id=expense.id) }}" class="btn btn-warning btn-sm"><i class="fa fa-edit"></i></a>
                        <a href="/expense_delete/{{expense.id}}" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}}

src/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <br>
        <div class="col-md-4 mt-5">
            <h1 class="text-center">Connectez vous!</h1>
            <br />
            <form action="" method="POST">
              <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" id="email" class="form-control" name="email" aria-describedby="emailHelp">
              </div>
              <div class="mb-3">
                <label for="password" class="form-label">Mot de passe</label>
                <input type="password" id="password" class="form-control" name="password">
              </div>
              <button type="submit" class="btn btn-secondary">Login</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}}

src/templates/projects.html
{% extends 'base.html' %}

{% block title %}Détails Projet{% endblock %}}

{% block content %}
    <h1  class="text-center bg-secondary text-white mt-3">Gestion projets</h1>
    <div>
        <div class="row justify-content-center">
            <br>
            <div class="form-card col-md-4 mt-5">
                <h5 class="text-center bg-primary-subtle text-white p-3 rounded">Création Projet</h5>
                <br />
                <form action="" method="POST">
                  <div class="mb-3">
                    <label for="title" class="form-label">Intitulé</label>
                    <input type="text" id="title" class="form-control" name="title" aria-describedby="emailHelp">
                  </div>
                  <div class="mb-3">
                    <input class="form-check-input" type="checkbox" name="active" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        Encours
                    </label>
                  </div>
                  <div class="mb-3">
                    <label for="description" class="form-label">Détails</label>
                      <textarea id="description" class="form-control" name="description"></textarea>
                  </div>
                  <div class="row">
                      <div class="mb-3 col">
                        <label for="date_start" class="form-label">Date début</label>
                        <input type="date" id="date_start" class="date_class form-control" name="date_start">
                      </div>
                      <div class="mb-3 col">
                        <label for="date_end" class="form-label">Date fin provisoire</label>
                        <input type="date" id="date_end" class="date_class form-control" name="date_end">
                      </div>
                  </div>
                  <div class="row">
                      <div class="mb-3 col">
                        <label for="estimated_cost" class="form-label">Coût estimé</label>
                        <input type="number" id="estimated_cost" class="form-control" name="estimated_cost">
                      </div>
                      <div class="mb-3 col">
                        <label for="estimated_revenue" class="form-label">Revenu estimé</label>
                        <input type="number" id="estimated_revenue" class="form-control" name="estimated_revenue">
                      </div>
                  </div>
                  <div class="row">
                  <button type="submit" class="btn btn-secondary btn-block">Créer</button>
                  </div>
                    <br />
                </form>
            </div>

            <div class="table-card">
                <h3>Nos projets</h3>
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Intitulé</th>
                      <th scope="col">Ecours</th>
                      <th scope="col">Responsable</th>
                      <th> Coût estimatif</th>
                      <th> Revenu estimatif</th>
                      <th scope="col">Début</th>
                      <th scope="col">Fin</th>
                      <th scope="col">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for project in projects%}
                    <tr>
                      <th scope="row">{{ project.id }}</th>
                      <td>{{ project.title }}</td>
                      <td>{% if project.active %} <span class="badge success">Oui</span> {% else %} <span class="badge warning">Non</span> {% endif %}</td>
                      <td>{{ project.user_rel.firstname }} {{ project.user_rel.lastname }}</td>
                      <td>{{ "{:,.0f}".format(project.estimated_cost) }}</td>
                      <td>{{ "{:,.0f}".format(project.estimated_revenue) }}</td>
                      <td>{{ project.date_start.strftime('%d-%m-%Y') }}</td>
                      <td>{{ project.date_end.strftime('%d-%m-%Y') }}</td>
                      <td>
                        <a href="{{ url_for('views.project_edit', id=project.id) }}" class="btn btn-warning btn-sm"><i class="fa fa-edit"></i></a>
                        <a href="/project_delete/{{project.id}}" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}}

src/templates/sales.html
{% extends 'base.html' %}

{% block title %}Ventes{% endblock %}}

{% block content %}
    <h1 class="text-center bg-secondary text-white mt-3">Suivi ventes</h1>
    <div>
        <div class="row justify-content-center">
            <br>
            <div class="form-card col-md-4 mt-5">
                <h5 class="text-center bg-primary-subtle text-white p-3 rounded">Saisie vente</h5>
                <br />
                <form action="" method="POST">
                  <div class="mb-3">
                    <label for="amount" class="form-label">Montant</label>
                    <input type="number" id="amount" class="form-control" name="amount" aria-describedby="emailHelp">
                  </div>
                  <div class="mb-3">
                    <label for="description" class="form-label">Libellé</label>
                      <textarea id="description" class="form-control" name="description"></textarea>
                  </div>
                  <div class="row">
                      <div class="mb-3 col">
                        <label for="date_transaction" class="form-label">Date opération</label>
                        <input type="date" id="date_transaction" class="date_class form-control" name="date_transaction">
                      </div>
                      <div class="mb-3 col">
                        <label for="projet_id" class="form-label">Projet lié</label>
                          <select class="choice_class form-control" name="project_id" id="projet_id">
                              <option value="">Choisir projet..</option>
                              {% for project in projects %}
                              <option value="{{ project.id }}">{{ project.title }}</option>
                              {% endfor %}
                          </select>
                      </div>
                  </div>
                  <div class="row">
                  <button type="submit" class="btn btn-secondary btn-block">Ajouter</button>
                  </div>
                    <br />
                </form>
            </div>

            <div>
                <br />
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Intitulé</th>
                      <th scope="col">Montant</th>
                      <th> Date dépense</th>
                      <th> Saisie par</th>
                      <th scope="col">Projet lié</th>
                      <th scope="col">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for sale in sales %}
                    <tr>
                      <th scope="row">{{ sale.id }}</th>
                      <td>{{ sale.description }}</td>
                      <td>{{ "{:,.0f}".format(sale.amount) }}</td>
                      <td>{{ sale.date_transaction.strftime('%d-%m-%Y') }}</td>
                      <td>{{ sale.user_rel.firstname }} {{ sale.user_rel.lastname }}</td>
                      <td>{{ sale.business_rel.title }}</td>
                      <td>
                        <a href="{{ url_for('views.sale_edit', id=sale.id) }}" class="btn btn-warning btn-sm"><i class="fa fa-edit"></i></a>
                        <a href="/sale_delete/{{sale.id}}" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}}